### ISSUE TITLE
DynaForm Content Probelm

### ISSUE THREAD

**Issue by Muhammadsh** [ethnp/pmangular#2]
Hello Mr. Ethan.
I'm currently developing a processmaker mobile application using REST api.
I've seen your amazing video 'Using the ProcessMaker RESTful API to Build a Custom Front End in AngularJS'. I noticed that you use dynaform_content to get data of a dynaform including its fields and  fields properties.
you've used the next api to get dyn_content from 'workflow' database:
/api/1.0/workflow/project/:prj_uid/dynaform/:dyn_uid
But for me this didn't work, the data into dynaForm table didn't insert correctly and the column dyn_content is null for all the rows.
So could you tell me what processmaker version have you used? and did you used a 'exe' version or 'zip'?
with regard.

**Comment by ethnp** [comment]
I used ProcessMaker 3.0. You need to design your process with the new bpmn2.0 designer and html5 responsive web design form editor or else it won't work.
It should work for both the exe and the zip.
