### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gusreyes01** [ethnp/pmangular#4]
Is there any guide on how to build this project? I've tried running gulp but I get the following error:

```
/Users/gustavo/Desktop/processmaker/repos/pmangular/node_modules/yamljs/lib/Parser.js:375
        throw new ParseException('Reference "' + value + '" does not exist.', this.currentLine);
        ^
Error: Reference "" does not exist.
```

**Comment by ethnp** [comment]
Did you run npm install? Also, you need to run gulp default to build all of it.

**Comment by gusreyes01** [comment]
Found my error: I changed   **scope: view_processes** edit_processes for **scope: * ** and apparently messed up the config.yml file. Thanks!

**Comment by gusreyes01** [comment]
I did ran `npm install` successfully and `gulp default` is what it's throwing the error.
